name: itk-viewer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - hypha
    - python-dotenv
    - -e ./packages/agave-renderer
    - -e ./packages/remote-image
    - itkwasm-image-io
