name: Build and test

on: [push, pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test with Electron
        uses: cypress-io/github-action@v6
        with:
          command: pnpm run test
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test with Chrome
        uses: cypress-io/github-action@v6
        with:
          install: false
          component: true
          browser: chrome
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Error: "The browser never connected."
      # - name: Test with Firefox
      #   uses: cypress-io/github-action@v6
      #   with:
      #     install: false
      #     component: true
      #     browser: firefox
      #   env:
      #     CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
