name: Build and test

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install --location global pnpm
          pnpm install

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Test
        uses: cypress-io/github-action@v5
        with:
          build: pnpm run build
          start: pnpm run test:ci
          record: true
          component: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: cypress:*

  # Not quite read for automated publication
  #- name: Publish
  #env:
  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #run: |
  #git config --global user.name "GitHub Actions"
  #git config --global user.email "itk+community@discourse.itk.org"
  #npx semantic-release
